name: Check Python with linters and pytest

on:
  pull_request:
    branches:
      # Against branch main, not the original branch name
      - main
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11-dev"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          # dev also installs the regular requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint with flake8 # Has an annotator
        uses: TrueBrain/actions-flake8@v2
      - name: Lint with mypy # Has an annotator
        uses: jpetrucciani/mypy-check@master
        with:
          requirements_file: requirements-dev.txt
      - name: Install annotator plugin for pytest
        run: pip install pytest-github-actions-annotate-failures
      - name: Test with pytest
        run: |
          python -m pytest tests/
