name: Check Python formatting in PRs

on: [pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    concurrency:
      group: black-${{ github.event.pull_request.number || github.ref }}
      # note: If you use only_check_changed_files, you do not want cancel-in-progress
      cancel-in-progress: true
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade black
      - name: Check formatting with black
        run: |
          black calculator tests
      - name: Annotate black changes using reviewdog
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: black
          fail_on_error: true

  isort:
    runs-on: ubuntu-latest
    concurrency:
      group: isort-${{ github.event.pull_request.number || github.ref }}
      # note: If you use only_check_changed_files, you do not want cancel-in-progress
      cancel-in-progress: true
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade isort
      - name: Reformat using isort
        run: |
          isort calculator tests
      - name: Annotate isort changes using reviewdog
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: isort
          fail_on_error: true
